{{-- Hugeicons (https://hugeicons.com) — generated by abduns/hugeicons-flux. Do not edit by hand. --}}

@php $attributes = $unescapedForwardedAttributes ?? $attributes; @endphp

@props([
    'variant' => 'outline',
])

@php
    $resolved = 'stroke-rounded';

    $classes = Flux::classes('shrink-0')->add(match ($variant) {
        'mini' => '[:where(&)]:size-5',
        'micro' => '[:where(&)]:size-4',
        default => '[:where(&)]:size-6',
    });
@endphp

@switch($resolved)
@case('stroke-rounded')
<svg {{ $attributes->class($classes) }} data-flux-icon aria-hidden="true" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none">
    <path d="M3 6H21" stroke="currentColor" stroke-linecap="round" stroke-width="1.5" />
    <path d="M3 10H10.5" stroke="currentColor" stroke-linecap="round" stroke-width="1.5" />
    <path d="M13.5 10L21 10" stroke="currentColor" stroke-linecap="round" stroke-width="1.5" />
    <path d="M3 14H7" stroke="currentColor" stroke-linecap="round" stroke-width="1.5" />
    <path d="M10 14H14" stroke="currentColor" stroke-linecap="round" stroke-width="1.5" />
    <path d="M17 14H21" stroke="currentColor" stroke-linecap="round" stroke-width="1.5" />
    <path d="M3 18H5.11765M8.29412 18H10.4118M13.5882 18H15.7059M18.8824 18H21" stroke="currentColor" stroke-linecap="round" stroke-width="1.5" />
</svg>
@break
@endswitch
