{{-- Hugeicons (https://hugeicons.com) — generated by abduns/hugeicons-flux. Do not edit by hand. --}}

@php $attributes = $unescapedForwardedAttributes ?? $attributes; @endphp

@props([
    'variant' => 'outline',
])

@php
    $resolved = 'stroke-rounded';

    $classes = Flux::classes('shrink-0')->add(match ($variant) {
        'mini' => '[:where(&)]:size-5',
        'micro' => '[:where(&)]:size-4',
        default => '[:where(&)]:size-6',
    });
@endphp

@switch($resolved)
@case('stroke-rounded')
<svg {{ $attributes->class($classes) }} data-flux-icon aria-hidden="true" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none">
    <circle cx="9" cy="4" r="2" stroke="currentColor" stroke-linecap="round" stroke-width="1.5" />
    <circle cx="19" cy="7" r="2" stroke="currentColor" stroke-linecap="round" stroke-width="1.5" />
    <circle cx="20" cy="20" r="2" stroke="currentColor" stroke-linecap="round" stroke-width="1.5" />
    <circle cx="4" cy="18" r="2" stroke="currentColor" stroke-linecap="round" stroke-width="1.5" />
    <path d="M10.9171 4.5752L17.0848 6.4255M19.1544 8.99455L19.8476 18.0061M18.0162 19.7523L5.98574 18.2484M8.32812 5.88435L4.67383 16.1164" stroke="currentColor" stroke-linecap="round" stroke-width="1.5" />
</svg>
@break
@endswitch
