{{-- Hugeicons (https://hugeicons.com) — generated by abduns/hugeicons-flux. Do not edit by hand. --}}

@php $attributes = $unescapedForwardedAttributes ?? $attributes; @endphp

@props([
    'variant' => 'outline',
])

@php
    $resolved = 'stroke-rounded';

    $classes = Flux::classes('shrink-0')->add(match ($variant) {
        'mini' => '[:where(&)]:size-5',
        'micro' => '[:where(&)]:size-4',
        default => '[:where(&)]:size-6',
    });
@endphp

@switch($resolved)
@case('stroke-rounded')
<svg {{ $attributes->class($classes) }} data-flux-icon aria-hidden="true" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none">
    <path d="M11 16.5C11 16.5 12.5 17 13.25 19C13.25 19 16.8235 13.1667 20 12" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" />
    <path d="M4 5H18" stroke="currentColor" stroke-linecap="round" stroke-width="1.5" />
    <path d="M4 10H15" stroke="currentColor" stroke-linecap="round" stroke-width="1.5" />
    <path d="M4 15H8" stroke="currentColor" stroke-linecap="round" stroke-width="1.5" />
</svg>
@break
@endswitch
