{{-- Hugeicons (https://hugeicons.com) — generated by abduns/hugeicons-flux. Do not edit by hand. --}}

@php $attributes = $unescapedForwardedAttributes ?? $attributes; @endphp

@props([
    'variant' => 'outline',
])

@php
    $resolved = 'stroke-rounded';

    $classes = Flux::classes('shrink-0')->add(match ($variant) {
        'mini' => '[:where(&)]:size-5',
        'micro' => '[:where(&)]:size-4',
        default => '[:where(&)]:size-6',
    });
@endphp

@switch($resolved)
@case('stroke-rounded')
<svg {{ $attributes->class($classes) }} data-flux-icon aria-hidden="true" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none">
    <path d="M2 12H22" stroke="currentColor" stroke-linecap="round" stroke-width="1.5" />
    <path d="M12 22L12 2" stroke="currentColor" stroke-linecap="round" stroke-width="1.5" />
    <path d="M21 8C18.2386 8 16 5.76142 16 3" stroke="currentColor" stroke-linecap="round" stroke-width="1.5" />
    <path d="M3 16C5.76142 16 8 18.2386 8 21" stroke="currentColor" stroke-linecap="round" stroke-width="1.5" />
</svg>
@break
@endswitch
