{{-- Hugeicons (https://hugeicons.com) — generated by abduns/hugeicons-flux. Do not edit by hand. --}}

@php $attributes = $unescapedForwardedAttributes ?? $attributes; @endphp

@props([
    'variant' => 'outline',
])

@php
    $resolved = 'stroke-rounded';

    $classes = Flux::classes('shrink-0')->add(match ($variant) {
        'mini' => '[:where(&)]:size-5',
        'micro' => '[:where(&)]:size-4',
        default => '[:where(&)]:size-6',
    });
@endphp

@switch($resolved)
@case('stroke-rounded')
<svg {{ $attributes->class($classes) }} data-flux-icon aria-hidden="true" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none">
    <path d="M18 8.5L5.9999 8.4999" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" />
    <path d="M21 12.5L3 12.5" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" />
    <path d="M16 21.5L16 15.5M16 15.5L18 17.5M16 15.5L14 17.5" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" />
    <path d="M12 8.5L12 2.5M12 2.5L14 4.5M12 2.5L10 4.5" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" />
    <path d="M8 21.5L8 15.5M8 15.5L10 17.5M8 15.5L6 17.5" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" />
</svg>
@break
@endswitch
