{{-- Hugeicons (https://hugeicons.com) — generated by abduns/hugeicons-flux. Do not edit by hand. --}}

@php $attributes = $unescapedForwardedAttributes ?? $attributes; @endphp

@props([
    'variant' => 'outline',
])

@php
    $resolved = 'stroke-rounded';

    $classes = Flux::classes('shrink-0')->add(match ($variant) {
        'mini' => '[:where(&)]:size-5',
        'micro' => '[:where(&)]:size-4',
        default => '[:where(&)]:size-6',
    });
@endphp

@switch($resolved)
@case('stroke-rounded')
<svg {{ $attributes->class($classes) }} data-flux-icon aria-hidden="true" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none">
    <path d="M5.5 3V11.5C5.5 15.0899 8.41015 18 12 18C15.5899 18 18.5 15.0899 18.5 11.5V3" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" />
    <path d="M3 21H21" stroke="currentColor" stroke-linecap="round" stroke-width="1.5" />
</svg>
@break
@endswitch
