{{-- Hugeicons (https://hugeicons.com) — generated by abduns/hugeicons-flux. Do not edit by hand. --}}

@php $attributes = $unescapedForwardedAttributes ?? $attributes; @endphp

@props([
    'variant' => 'outline',
])

@php
    $resolved = 'stroke-rounded';

    $classes = Flux::classes('shrink-0')->add(match ($variant) {
        'mini' => '[:where(&)]:size-5',
        'micro' => '[:where(&)]:size-4',
        default => '[:where(&)]:size-6',
    });
@endphp

@switch($resolved)
@case('stroke-rounded')
<svg {{ $attributes->class($classes) }} data-flux-icon aria-hidden="true" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none">
    <circle cx="12" cy="12" r="10" stroke="currentColor" stroke-linecap="round" stroke-width="1.5" />
    <path d="M2 12C7.18491 16.8269 16.4642 16.3877 22 12.3556" stroke="currentColor" stroke-width="1.5" />
    <path d="M11.5368 2C6.98939 6.5 6.48408 17 11.9941 22" stroke="currentColor" stroke-width="1.5" />
</svg>
@break
@endswitch
